version: 2
jobs:
  build:
    working_directory: ~/deepdos
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            pip install --user -r requirements.txt
      - run:
          command: |
            export PATH="~/.local/bin:$PATH"
      - run:
          command: |
            pytest
    
